language: ruby
rvm:
  - 2.1.0
script: bundle exec rspec spec
addons:
  sauce_connect:
    username: "biblejeopardy"
    access_key: 
      secure: "MLTu5n2bef7qjfldeH3dk9PPYE9miPRu6hXEEqDdQaZiK2BLi1Ib9y4N0ct9do0wQX2FIXCLrnbB63RmSH3nudaBAm9XF1avrPrbQLUVDGvQH+B5/5w/sGngMdhGcQzzuA7t+dM0W3I5giX5HxvBvR0/MOTOgIi3ZSlK0eqGlJs="