development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5

test: &test
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: bible_jeopardy_test
  pool: 5
  username: bible_jeopardy
  password: Katalyst2

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: bible_jeopardy_production
  pool: 5
  username: bible_jeopardy
  password: Katalyst2

cucumber:
  <<: *test